pipeline:
  build:
    image: node:latest
    commands:
      - yarn
      - yarn run coverage
      - yarn run eslint
  test:
    secrets: [sonar_host,sonar_token]
    image: ubuntu:latest
    commands:
      - env
  sonar:
    image: aosapps/drone-sonar-plugin:1.0
    settings:
        sonar_host:
          from_secret: sonar_host
        sonar_token:
          from_secret: sonar_token
        level: DEBUG
        ver: 1.0
        showProfiling: true
