kind: pipeline
type: docker
name: nodejs
steps:
- name: build
  image: node:latest
  commands:
    - yarn
    - yarn run coverage:ci
    - yarn run eslint:ci
- name: sonar
  image: aosapps/drone-sonar-plugin:latest
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
    ver: 1.0
    sources: src/
    exclusions: docs/**/*
- name: clean
  image: node:latest
  commands:
    - rm -rf ./*
