kind: pipeline
type: docker
name: nodejs
steps:
- name: build
  image: node:latest
  commands:
    - yarn
    - yarn run coverage:ci
    - yarn run eslint:ci
- name: sonar
  image: fmetais/drone-sonar-scan-plugin:latest
  settings:
    sonar.host.url: 
      from_secret: sonar_host
    sonar.login: 
      from_secret: sonar_token
