pipeline:
  build:
    image: node:latest
    commands:
      - yarn
      - yarn run coverage
      - yarn run eslint
  sonar:
    image: aosapps/drone-sonar-plugin:1.0
    secrets: [sonar_host, sonar_token]

